;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/DataTable/DT_MyMonsterTag.DT_MyMonsterTag
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooltime.Gimmick.HealZone",DevComment="")
+GameplayTagList=(Tag="Cooltime.Skill.Flash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Gimmick.HealZone",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Skill.Flash",DevComment="Flash skill\'s tag.")
+GameplayTagList=(Tag="GameplayCue.Skill.Ignite",DevComment="")
+GameplayTagList=(Tag="Gimmick.Heal.HealZone",DevComment="")
+GameplayTagList=(Tag="Skill.Attack.Ignite",DevComment="")
+GameplayTagList=(Tag="Skill.Move.Flash",DevComment="Teleport in near place")

